server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: discovery
  config:
    import:
      configserver: ${SERVER_CONFIG:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: ${SERVER_DISCOVERY:http://localhost:8081/eureka}
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false #Ожидание удаления сервера и отключения порога безопасности
