version: '3.7'
services:
  redis:
    image: cloud-redis:1.0
    restart: always
    container_name: cloud-redis-container
    logging:
      driver: 'json-file'
      options:
        max-size: '30m'
        max-file: '10'
    deploy:
      resources:
        limits:
          memory: 256M
    command: redis-server --requirepass 1111
    ports:
      - 6379:6379
    networks:
      - cloud-network-my

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=default:redis:6379:0:1111,test:redis:6379:1:1111
    ports:
      - "8099:8081"
    networks:
      - cloud-network-my

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch_springboot
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana_springboot
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    networks:
      - cloud-network-my

  logstash:
    image: docker.elastic.co/logstash/logstash:8.3.3
    container_name: logstash_springboot
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - cloud-network-my
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
    driver: local

networks:
  cloud-network-my:
    driver: bridge