version: '3.7'
services:
  redis:
    image: cloud-redis:1.0
    restart: always
    container_name: cloud-redis-container
    logging:
      driver: 'json-file'
      options:
        max-size: '30m'
        max-file: '10'
    deploy:
      resources:
        limits:
          memory: 256M
    command: redis-server --requirepass 1111
    ports:
      - 6379:6379
    networks:
      - cloud-network-my
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=default:redis:6379:0:1111,test:redis:6379:1:1111
    ports:
      - "8099:8081"
    networks:
      - cloud-network-my

networks:
  cloud-network-my:
    driver: bridge