server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: gateway
  config:
    import:
      configserver: ${SERVER_CONFIG:http://localhost:8888}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${SERVER_DISCOVERY:http://localhost:8081/eureka}

