server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: facade
  config:
    import: configserver:${SERVER_CONFIG:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: ${SERVER_DISCOVERY:http://localhost:8889/eureka}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full