server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: order
  config:
    import: configserver:${SERVER_CONFIG:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: ${SERVER_DISCOVERY:http://localhost:8889/eureka}
  instance:
    instance-id: ${random.value}